version: "3"

services:
  php-fpm:
    build: docker/php-fpm
    container_name: breweries_php_fpm
    volumes:
      - ./:/var/www/html

  nginx:
    build: docker/nginx
    container_name: breweries_nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
      - mysql-db

  mysql-db:
    build: docker/mysql
    container_name: breweries_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=brewery
      - MYSQL_ROOT_PASSWORD=root

  schedule:
    build: docker/schedule
    container_name: brweries_schedule
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-db

  queue:
    build: docker/queue
    command: php artisan queue:work
    container_name: brweries_queue
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-db
      - schedule



